import { createHash } from 'node:crypto';

/** Facebook / LinkedIn / X recommended Open Graph size (≈1.91:1). */
export const OG_WIDTH = 1200;
export const OG_HEIGHT = 630;

/** Default share card (homepage, blog indexes, 404). Generated by `npm run generate:og`. */
export const DEFAULT_OG_IMAGE = '/media/og/share-home.jpg';

/** Stable public path for a featured image cover-cropped to 1200×630. */
export function ogPathForFeaturedImage(featuredImage: string): string {
  const key = featuredImage.replace(/^\/+/, '');
  const hash = createHash('sha1').update(key).digest('hex').slice(0, 16);
  return `/media/og/posts/${hash}.jpg`;
}
